name: Inpet Console CD

env:
  
  REGISTRY: ${{ secrets.REGISTRY }}
  REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: msawood-stage
  APP_NAME: "inpet-console-ui"
  TAG: ""


on:
  # Trigger the workflow on push to the master branch
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Determine tag
      if: env.TAG == ''
      run: |
        echo "TAG=${GITHUB_SHA::7}" | tee -a $GITHUB_ENV
    - name: build from dockerfile
      id: image-build
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.APP_NAME }}
        tags: latest ${{ env.TAG }}
        dockerfiles: |
          ./Dockerfile
    - name: Push to registry
      id: push-to-registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.image-build.outputs.image }}
        tags: ${{ steps.image-build.outputs.tags }}
        registry: ${{ env.REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
    # - name: Install oc
    #   uses: redhat-actions/oc-installer@v1
    #   with:
    #     oc_version: '4.6'
    # - name: Authenticate and set context
    #   uses: redhat-actions/oc-login@v1
    #   with:
    #     openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
    #     openshift_token: ${{ env.OPENSHIFT_TOKEN }}
    #     insecure_skip_tls_verify: true
    #     namespace: ${{ env.OPENSHIFT_NAMESPACE }}
    # - name: Deploy
    #   run: oc process --local -f k8s/template.yaml -p IMAGE_TAG=${{ env.TAG }} | oc apply -f -